### ISSUE TITLE
Sandboxie package isn't automated anymore

### ISSUE THREAD

**Issue by Jackenmen** [jack1142/choco-auto#1]
Might be hard to get download links from sophos's website due to its export compliance form. Sandboxie will be made open source soon so might not be worth fixing.

**Comment by Jackenmen** [comment]
Update: Week ago I asked for redistribution rights from Sandboxie's developers, but sadly they didn't agree for embedding the installer in package due to strict export restrictions. This means that the package can't be worked on right now.

**Comment by B4rabbas** [comment]
I doubt they will make their software open source one day if today they 're already disagreeing to redistribute it from a choco repo...

Anyway many thanks for your work of maintainer.

**Comment by Jackenmen** [comment]
In case you're interested in the response I got from them back then:
> Hello,
> 
> I'm afraid we cannot permit this due to strict export restrictions on
technology imposed by law.
> Please DO NOT distribute the binary code.
>
> Thank you for understanding

I'm hoping they really will pursue open source transition but I'm doubting it's their priority when they don't earn money from it 😕

**Comment by mustelid** [comment]
Perhaps you can migrate to the new GPLv3 release?
[https://github.com/xanasoft/Sandboxie](https://github.com/xanasoft/Sandboxie)

**Comment by majkinetor** [comment]
Why not embedding this version manually and call it  a day ?

**Comment by Jackenmen** [comment]
@majkinetor I want this package to use https://github.com/sandboxie/sandboxie (by one of old sandboxie developers) which still haven't had a release. 
The one release which used sandboxie-plus on sandboxie chocolatey package was a mistake and
I should make a separate choco package for sandboxie-plus repository which I just still haven't gotten around to. I'll see what I can do about that today, but sandboxie chocolatey package will use the repo I linked above as it's supposed to be more closely resembling the original development (although I am kind of disappointed, there's still no release on that front).

**Comment by majkinetor** [comment]
I think last official version should be released and embedded given it csn be redistributed. This could be manually done. We dont know if foss variant will evwr get release.

**Comment by Jackenmen** [comment]
> I think last official version should be released and embedded given it csn be redistributed

I am not sure whether the last version released by Sophos (5.33.6) can actually be redistributed (the previous versions definitely couldn't be, as said in the response from Sophos above).

**Comment by majkinetor** [comment]
Ah, ok, I didn't see they forbid it. Nothing to do here then except releasing sandboxie+.
