### ISSUE TITLE
[sublimetext4, sandboxie.install] Packages do not have an icon

### ISSUE THREAD

**Issue by Jackenmen** [jack1142/choco-auto#4]

**Comment by isaak654** [comment]
I'm not sure if this is still an issue, I can see the icons in https://community.chocolatey.org/packages?q=sandboxie

**Comment by Jackenmen** [comment]
Hmm, looking at the git blame it seems that the icons were always there for both sublimetext4 and sandboxie.install packages, I wonder why I made this :thinking: 

Thanks for letting me know this can be closed :)
