### ISSUE TITLE
[sandboxie-plus.install] ARM64 installer is missing in Chocolatey

### ISSUE THREAD

**Issue by isaak654** [jack1142/choco-auto#5]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
You should include the new [ARM64 installer](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.5.0) in `sandboxie-plus.install` package.

* **What is the current behavior?**
https://github.com/jack1142/choco-auto/commit/906ae1c761ee1ae712139887737a7ac78f83ed0a

* **What is the expected behavior?**
ARM64 installer support: 
`https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.5.0/Sandboxie-Plus-ARM64-v1.5.0.exe`

**Comment by Jackenmen** [comment]
It doesn't seem like Chocolatey provides much support for ARM64
https://github.com/chocolatey/choco/issues/1803
