### ISSUE TITLE
[sublimetext4] Feature: add Sublime Text binary shims, or add PATH support

### ISSUE THREAD

**Issue by koitsu** [jack1142/choco-auto#6]
# Problem

After installing `sublimetext4`, I found I could not run `subl.exe` from a Command Prompt.

I don't think it matters, but, I actually install `sublimetext4` in a non-stock location as such (via Command Prompt):

>  choco install sublimetext4 --install-args="/DIR=""D:\Util\Sublime"""

The `/DIR` argument is passed to the Sublime Text installer, which is the Inno Setup suite, and is [described here in detail](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline).  The "extra double quotes" are needed as a side effect of Command Prompt parsing (even though the path lacks spaces, I take no chances).

# Details

Currently the `sublimetext4` package, when installed, does not provide immediate access to [the Command Line tools](https://www.sublimetext.com/docs/command_line.html) that comes with Sublime Text.  As described: `subl.exe` is not available immediately after the Chocolatey package is installed.

# Fix

There are two methods:

1. Leverage Chocolatey's [shimming feature](https://docs.chocolatey.org/en-us/features/shim), which would add a shim of subl.exe to the `($env:ChocolateyInstall)\bin` path
1. Leverage Chocolatey's [Install-ChocolateyPath](https://docs.chocolatey.org/en-us/create/functions/install-chocolateypath) function, to modify the PATH environment variable, to contain the path of wherever `sublimetext4` was installed

Option 1 is easier and safer, and is what most things use.  However, I don't know how to inform Chocolatey via its PowerShell functions how to install a shim.  I have not read the docs on shimming in full, however.

Option 2 is more complicated for one specific reason: you have to define whether or not the PATH to modify is the user-level PATH (i.e. `Install-ChocolateyPath -PathType User`), or the system-level PATH (i.e. `Install-ChocolateyPath -PathType User`).  Which to choose depends" on "how" SublimeText was installed (for all users, or just the user that ran Chocolatey).  I personally am not big on things modifying my PATH dynamically and I've found older version of Chocolatey messing up my PATH quite badly (these were fixed in 1.2.0); the shimming model has never failed me, even after package upgrades.

# Workaround

For now, I'm manually adding the Sublime Text installation location to my user PATH environment var.

**Comment by Jackenmen** [comment]
Oh yeah, I should totally add shims, I use `subl` extensively.

**Comment by Jackenmen** [comment]
If you want to try PRing this then you'll want to add this at the end of install script:
`Install-BinFile "subl" "$install Location\subl.exe`
And this at the end of uninstall script:
`Uninstall-BinFile "subl"`

You would have to figure out how to properly determine install location since the shim location depends on it.

**Comment by koitsu** [comment]
I'll give it a shot. Thanks!

**Comment by Jackenmen** [comment]
Fixed by #7
