### ISSUE TITLE
[sandboxie] Bug: install script leaves installer shims

### ISSUE THREAD

**Issue by Destroy666x** [jack1142/choco-auto#8]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

The Chocolatey package leaves installer shims in `C:\ProgramData\chocolatey\bin`

* **If the current behavior is a bug, please provide the steps to reproduce the problem**:

1. Install with choco
2. Update with choco
3. Check `C:\ProgramData\chocolatey\bin` - multiple exes will be there

* **What is the expected behavior?**

Only one executable in that dir, for sandboxie, if any. Perhaps one for the main executable, defined by `.gui` file.

* **What is the motivation / use case for changing the behavior?**

Avoid chaos in there, easier to call through CLI if without a version.

* **Please tell us about your environment:**

  - Choco package name: `sandboxie`
  - Version: any

**Comment by Destroy666x** [comment]
Shims aren't documented too well IMO, but here's what actually happens:

- you're downloading installer to `chocolatey\lib\sandboxie-plus.install` kind of folder in `chocolateyInstall.ps1`
- you're not deleting that installer after it finishes the job
- Chocolatey automatically shims anything in that dir or subdirs after installer script finishes

Possible solutions:
- download the installer somewhere else if it's needed later for any reason (e.g. is it required for uninstalling? no idea)
- delete the installer at the end of install script if it's not needed, so `Remove-Item "$toolsPath\Sandboxie-Plus-x86-v1.10.5.exe"`

@Jackenmen

**Comment by Jackenmen** [comment]
Oh, it's about shims for the installer. Installers in embedded packages are generally ignored by using a `.ignore` file (see: https://docs.chocolatey.org/en-us/features/shim#i-need-to-exclude-a-file-from-shimming)

I'll fix it, thanks for investigating this further.

**Comment by Jackenmen** [comment]
I was a bit wrong, installers in embedded packages are actually removed but a `.ignore` file is added if the removal fails. Either way, this is now fixed.
